export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];


export const testimonials = [
  {
    name: 'Parry Hotter',
    location: 'Belgrade',
    img: '/hary.jpg',
    comment: 'We rented a car from this website and had an amazing experience! The booking was easy and the rental rates were very affordable.'
  },
  {
    name: 'Ron Rizzly',
    location: 'Novi Sad',
    img: '/ron.jpg',
    comment: 'The car was in great condition and made our trip even better. Highly recommend for this car rental website!'
  },
]


export const carsDB: Car[] = [
  {
      id: '1',
      name: 'Mercedes-Benz E-Class',
      brand: 'Mercedes-Benz',
      img: 'https://mediaim.expedia.com/cars/35/9c1c52d2-82b0-4b51-ac5a-9ef5106daee1.jpg?impolicy=resizecrop&ra=fit&rh=165&rw=165',
      type: 'Luxury',
      location: 'London Victoria Station',
      price: 168,
      mileage: 300,
      gear: 'Automatic',
      passengers: 5,
      doors: 5,
      ac: true,
  },
  {
      id: '2',
      name: 'MINI Cooper',
      brand: 'MINI_COOPER',
      img: 'https://mediaim.expedia.com/cars/35/e8d56d1a-27fd-49da-a37f-d30d80bb083e.jpg?impolicy=resizecrop&ra=fit&rh=165&rw=165',
      type: 'Compact',
      location: 'London Victoria Station',
      price: 77,
      mileage: 0,
      gear: 'Manual',
      passengers: 5,
      doors: 4,
      ac: true,
  },
  {
      id: '3',
      name: 'BMW X3',
      brand: 'BMW',
      img: 'https://mediaim.expedia.com/cars/35/0720e638-6aba-4346-94b6-b7d775ad4af4.jpg?impolicy=resizecrop&ra=fit&rh=165&rw=165',
      type: 'Luxury',
      location: 'London Victoria Station',
      price: 200,
      mileage: 300,
      gear: 'Automatic',
      passengers: 5,
      doors: 5,
      ac: true,
  },
  {
      id: '4',
      name: 'BMW 520',
      brand: 'BMW',
      img: 'https://mediaim.expedia.com/cars/35/2d72a12f-0e7e-4ae1-a4ca-50b61c8c3315.jpg?impolicy=resizecrop&ra=fit&rh=165&rw=165',
      type: 'Premium',
      location: 'London Victoria Station',
      price: 139,
      mileage: 300,
      gear: 'Automatic',
      passengers: 5,
      doors: 5,
      ac: true,
  },
  {
      id: '5',
      name: 'BMW 5 Series Touring',
      brand: 'BMW',
      img: 'https://mediaim.expedia.com/cars/35/3a79a53f-6c24-408a-bcb7-363629191f32.jpg?impolicy=resizecrop&ra=fit&rh=165&rw=165',
      type: 'Premium',
      location: '22 Park Lane, London',
      price: 172,
      mileage: 300,
      gear: 'Automatic',
      passengers: 5,
      doors: 5,
      ac: true,
  },
  {
      id: '6',
      name: 'BMW 520',
      brand: 'BMW',
      img: 'https://mediaim.expedia.com/cars/35/2d72a12f-0e7e-4ae1-a4ca-50b61c8c3315.jpg?impolicy=resizecrop&ra=fit&rh=165&rw=165',
      type: 'Premium',
      location: 'London Victoria Station',
      price: 139,
      mileage: 0,
      gear: 'Automatic',
      passengers: 5,
      doors: 5,
      ac: true,
  },
  {
      id: '7',
      name: 'Nissan Sunny',
      brand: 'Nissan',
      img: 'https://www.sixt.de/php/fleet/vehicleimage?grp=EDAR&liso=EG&uci=43043',
      type: 'Economy',
      location: 'Alexandria, Egypt',
      price: 32,
      mileage: 0,
      gear: 'Automatic',
      passengers: 5,
      doors: 4,
      ac: true,
  },
  {
      id: '8',
      name: 'Toyota Corolla',
      brand: 'Toyota',
      img: 'https://d2f9dw3b0opbul.cloudfront.net/76d04ad441284d2a8a95d3c83a9036fc.jpg',
      type: 'Full Size',
      location: 'Dubai, United Arab Emirates',
      price: 89,
      mileage: 0,
      gear: 'Automatic',
      passengers: 5,
      doors: 4,
      ac: true,
  },
  {
      id: '9',
      name: 'Toyota Camry',
      brand: 'Toyota',
      img: 'https://d2f9dw3b0opbul.cloudfront.net/b48b8364ef8541a5b4fcd27dc2ba4e5b.png',
      type: 'Full Size',
      location: 'Dubai, United Arab Emirates',
      price: 90,
      mileage: 300,
      gear: 'Automatic',
      passengers: 5,
      doors: 4,
      ac: true,
  },
  {
      id: '10',
      name: 'MG ZS',
      brand: 'MG',
      img: 'https://d2f9dw3b0opbul.cloudfront.net/ab71289c3f594cb28c6fddca97b34c8f.png',
      type: 'Suv',
      location: 'Dubai, United Arab Emirates',
      price: 92,
      mileage: 300,
      gear: 'Automatic',
      passengers: 5,
      doors: 4,
      ac: true,
  },
  {
      id: '11',
      name: 'Hyundai Elantra',
      brand: 'Hyundai',
      img: 'https://d2f9dw3b0opbul.cloudfront.net/cd289e6fc019461cb124ef237327d479.png',
      type: 'Full Size',
      location: 'Dubai, United Arab Emirates',
      price: 96,
      mileage: 0,
      gear: 'Automatic',
      passengers: 5,
      doors: 4,
      ac: true,
  },
  {
      id: '12',
      name: 'Mercedes-Benz CLA',
      brand: 'Mercedes-Benz',
      img: 'https://d2f9dw3b0opbul.cloudfront.net/f3697694004045379dbecd9740179d19.jpg',
      type: 'Suv',
      location: 'Dubai, United Arab Emirates',
      price: 199,
      mileage: 250,
      gear: 'Automatic',
      passengers: 5,
      doors: 4,
      ac: true,
  },
  {
      id: '13',
      name: 'AUDI Q7',
      brand: 'Audi',
      img: 'https://d2f9dw3b0opbul.cloudfront.net/3c2a4b9f85e948ed8e98f744265e771c.png',
      type: 'Luxury',
      location: 'Dubai, United Arab Emirates',
      price: 248,
      mileage: 250,
      gear: 'Automatic',
      passengers: 7,
      doors: 5,
      ac: true,
  },
  {
      id: '14',
      name: 'Porsche 718 Boxster GTS',
      brand: 'Porsche',
      img: 'https://d2f9dw3b0opbul.cloudfront.net/a3c7aabe71c24016904e61cbaf754dfd.jpg',
      type: 'Convertible',
      location: 'Dubai, United Arab Emirates',
      price: 248,
      mileage: 250,
      gear: 'Automatic',
      passengers: 2,
      doors: 2,
      ac: true,
  },
  {
      id: '15',
      name: 'BMW 435',
      brand: 'BMW',
      img: 'https://platform.cstatic-images.com/xlarge/in/v2/stock_photos/9d7ce7cd-ae8f-4695-80db-c4a469020e3a/40c51eb1-216d-4ee6-89de-3780e0f2959b.png',
      type: 'Convertible',
      location: 'Dubai, United Arab Emirates',
      price: 212,
      mileage: 300,
      gear: 'Automatic',
      passengers: 2,
      doors: 2,
      ac: true,
  },
]